//
//  PlistDatesTests.m
//  JSONModelDemo_iOS
//
//  Created by Mark Aufflick on 6/07/13.
//  Copyright (c) 2013 Underplot ltd. All rights reserved.
//

#import "PlistDatesTests.h"
#import "DatesModel.h"

@implementation PlistDatesTests

- (void)testDatesFromPlist
{
    DatesModel* m;
    
    NSString* filePath = [[NSBundle bundleForClass:[JSONModel class]].resourcePath stringByAppendingPathComponent:@"dates.plist"];
    
    NSMutableArray * allowedSourceTypes = [[JSONModel defaultAllowedSourceTypes] mutableCopy];
    [allowedSourceTypes addObject:[NSDate class]];
    
    NSDictionary * sourceDict = [NSDictionary dictionaryWithContentsOfFile:filePath];
    NSAssert(sourceDict, @"Couldn't convert plist into dictionary (%@)", filePath);
    
    NSError* err;
    m = [[DatesModel alloc] initWithDictionary:sourceDict allowedSourceTypes:allowedSourceTypes error:&err];
    NSAssert(!err, [err localizedDescription]);
    
    NSAssert(m, @"Could not load the test data file. %@", filePath);
    
    NSDate * aDate = [NSDate dateWithString:@"2013-07-06 04:13:48 +0000"];
    
    STAssertEqualObjects(m.aDate, aDate, @"loaded date objects don't match");
    
    // test round trip
    NSDictionary * generatedDict =  [m toDictionary];
    NSAssert(generatedDict, @"toDictionary returned nil");
    
    STAssertEqualObjects(generatedDict, sourceDict, @"dictionary generated by toDictionary doesn't match source dictionary");
}

@end
